### ISSUE TITLE
Make compatible or unregister from npm

### ISSUE THREAD

**Issue by kamronbatman** [NicoJuicy/Numeral-js#1]
This repo is very confusing compared to the original npm module `numeral`.

Recommend the following:
- Remove commits added and submit as PR to original repo.
- Update master to match original repo and register versions to match original repo.

Otherwise, simply remove the registration to npm.

**Comment by phil-lgr** [comment]
I second the above, please unregister it. The package still points to the website, but it's 3 years old.

![image](https://user-images.githubusercontent.com/9644867/41617135-b36fc76c-73cd-11e8-974a-ed4657c77214.png)

Thanks
